import type { HomeAssistantActionContext, HomeAssistantActionHandler } from "./runtime.ts";

import {
  compactObject,
  nullableString,
  optionalBoolean,
  optionalRecord,
  optionalString,
  requiredRecord,
} from "../../core/cast.ts";
import { ProviderRequestError } from "../provider-runtime.ts";
import { runHomeAssistantCommands } from "./runtime-ws.ts";
import {
  assertStoredConfigMatches,
  badHomeAssistantRequest,
  readInputString,
  requireHomeAssistantChanges,
} from "./runtime.ts";

export const homeAssistantLovelaceActionHandlers: Record<string, HomeAssistantActionHandler> = {
  async get_lovelace_config(input, context) {
    try {
      const [config] = await runHomeAssistantCommands(context, [
        {
          type: "lovelace/config",
          ...compactObject({
            url_path: optionalString(input.urlPath),
            force: optionalBoolean(input.force),
          }),
        },
      ]);
      return { config: optionalRecord(config) ?? {} };
    } catch (error) {
      // Home Assistant answers both "no such dashboard" and "this dashboard has
      // no stored config" with the same code, and the second message is the
      // bare text "No config found." A dashboard rendered by a strategy,
      // including the auto-generated default one, is the common cause.
      if (error instanceof ProviderRequestError && error.status === 404) {
        throw new ProviderRequestError(
          404,
          `${error.message} This means either that no dashboard has the requested url path, or that the dashboard has no stored configuration because it is generated by a strategy.`,
        );
      }
      throw error;
    }
  },
  async save_lovelace_config(input, context) {
    const urlPath = optionalString(input.urlPath);
    const previousConfig = requiredRecord(input.previousConfig, "previousConfig", badHomeAssistantRequest);
    const config = requiredRecord(input.config, "config", badHomeAssistantRequest);

    // Home Assistant replaces the stored document wholesale and has no version
    // or etag to check, so a caller that never read the dashboard would silently
    // drop every view it did not happen to include. Require the current document
    // to be handed back, and refuse the write unless it still matches.
    assertStoredConfigMatches({
      stored: await readStoredLovelaceConfig(context, urlPath),
      previous: previousConfig,
      subject: "this dashboard",
      readActionName: "get_lovelace_config",
    });

    await runHomeAssistantCommands(context, [
      {
        type: "lovelace/config/save",
        config,
        ...compactObject({ url_path: urlPath }),
      },
    ]);
    return { saved: true };
  },
  async delete_lovelace_config(input, context) {
    await runHomeAssistantCommands(context, [
      {
        type: "lovelace/config/delete",
        ...compactObject({ url_path: optionalString(input.urlPath) }),
      },
    ]);
    return { deleted: true };
  },
  async list_lovelace_dashboards(_input, context) {
    const [dashboards] = await runHomeAssistantCommands(context, [{ type: "lovelace/dashboards/list" }]);
    return { dashboards: dashboards ?? [] };
  },
  async create_lovelace_dashboard(input, context) {
    const [dashboard] = await runHomeAssistantCommands(context, [
      {
        type: "lovelace/dashboards/create",
        url_path: readInputString(input.urlPath, "urlPath"),
        title: readInputString(input.title, "title"),
        ...compactObject({
          icon: optionalString(input.icon),
          show_in_sidebar: optionalBoolean(input.showInSidebar),
          require_admin: optionalBoolean(input.requireAdmin),
        }),
      },
    ]);
    return { dashboard: optionalRecord(dashboard) ?? {} };
  },
  async update_lovelace_dashboard(input, context) {
    const changes = compactObject({
      title: optionalString(input.title),
      // Home Assistant treats a null icon as "remove the icon" rather than as a
      // missing field, so it has to survive as null instead of being compacted.
      icon: nullableString(input.icon),
      show_in_sidebar: optionalBoolean(input.showInSidebar),
      require_admin: optionalBoolean(input.requireAdmin),
    });
    requireHomeAssistantChanges(changes, "title, icon, showInSidebar, or requireAdmin");

    const [dashboard] = await runHomeAssistantCommands(context, [
      {
        type: "lovelace/dashboards/update",
        dashboard_id: readInputString(input.dashboardId, "dashboardId"),
        ...changes,
      },
    ]);
    return { dashboard: optionalRecord(dashboard) ?? {} };
  },
  async delete_lovelace_dashboard(input, context) {
    await runHomeAssistantCommands(context, [
      {
        type: "lovelace/dashboards/delete",
        dashboard_id: readInputString(input.dashboardId, "dashboardId"),
      },
    ]);
    return { deleted: true };
  },
  async list_lovelace_resources(_input, context) {
    const [resources] = await runHomeAssistantCommands(context, [{ type: "lovelace/resources" }]);
    return { resources: resources ?? [] };
  },
  async create_lovelace_resource(input, context) {
    const [resource] = await runHomeAssistantCommands(context, [
      {
        type: "lovelace/resources/create",
        res_type: readInputString(input.resourceType, "resourceType"),
        url: readInputString(input.url, "url"),
      },
    ]);
    return { resource: optionalRecord(resource) ?? {} };
  },
  async update_lovelace_resource(input, context) {
    const changes = compactObject({
      res_type: optionalString(input.resourceType),
      url: optionalString(input.url),
    });
    requireHomeAssistantChanges(changes, "resourceType or url");

    const [resource] = await runHomeAssistantCommands(context, [
      {
        type: "lovelace/resources/update",
        resource_id: readInputString(input.resourceId, "resourceId"),
        ...changes,
      },
    ]);
    return { resource: optionalRecord(resource) ?? {} };
  },
  async delete_lovelace_resource(input, context) {
    await runHomeAssistantCommands(context, [
      {
        type: "lovelace/resources/delete",
        resource_id: readInputString(input.resourceId, "resourceId"),
      },
    ]);
    return { deleted: true };
  },
};

/**
 * Read the configuration a dashboard currently stores, treating "nothing stored"
 * as an empty document.
 *
 * A dashboard that has never been saved and a url path that does not exist both
 * report the same not-found, and they do not need to be told apart here: the
 * save that follows rejects an unknown dashboard on its own.
 */
async function readStoredLovelaceConfig(
  context: HomeAssistantActionContext,
  urlPath: string | undefined,
): Promise<Record<string, unknown>> {
  try {
    const [config] = await runHomeAssistantCommands(context, [
      { type: "lovelace/config", ...compactObject({ url_path: urlPath }) },
    ]);
    return optionalRecord(config) ?? {};
  } catch (error) {
    if (error instanceof ProviderRequestError && error.status === 404) {
      return {};
    }
    throw error;
  }
}
